# -*- coding: utf-8 -*-
"""TutorIA – a spanyol oldal kártyái (LOMLOE, 1–6. Primaria).

Bekötés a kartyak.py végén:
    from kartyak_es import KARTYAK_ES
    KARTYAK.extend(KARTYAK_ES)
"""

KARTYAK_ES: list[dict] = [
    {
        "id": "es_medio_3_cajal",
        "sorszam": 1,
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Iniciación en la actividad científica",
        "nev": "Santiago Ramón y Cajal",
        "alnev": "médico e investigador · 1852–1934",
        "kep": "medio_3_cajal",
        "ritkasag": "nagyon_ritka",
        "ero": 450,
        "kepesseg": "Neuronas",
        "kepesseg_ero": 380,
        "becenev": "EL DIBUJANTE DEL CEREBRO",
        "leiras": "Demostró que el cerebro no es una red continua, sino millones de células separadas que se hablan entre sí. Por eso recibió el Premio Nobel en 1906.",
        "teny": "Dibujó a mano miles de láminas de neuronas mientras miraba por el microscopio. Todavía hoy se usan en las facultades de medicina de todo el mundo.",
        "erdekesseg": "De niño quería ser pintor y su padre no se lo permitió. Al final fue su mano de dibujante la que le hizo famoso.",
        "idezet": "Todo hombre puede ser, si se lo propone, escultor de su propio cerebro.",
        "idezet_tipus": "idezet",
        "prompt": "Santiago Ramon y Cajal, balding head, short grey beard, deep-set intense eyes, dark late-19th-century jacket and waistcoat. Seated at his desk with one eye at a brass microscope, his own ink drawings of branching neurons pinned on the wall and spread across the desk. Warm lamplight and deep shadow."
    },
    {
        "id": "es_medio_2_mutis",
        "sorszam": 2,
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 2,
        "evfolyam": 4,
        "evfolyamok": [
            3,
            4
        ],
        "lecke": "La vida en nuestro planeta",
        "nev": "José Celestino Mutis",
        "alnev": "médico y botánico · 1732–1808",
        "kep": "medio_2_mutis",
        "ritkasag": "ritka",
        "ero": 320,
        "kepesseg": "Expedición botánica",
        "kepesseg_ero": 260,
        "becenev": "EL CAZADOR DE PLANTAS",
        "leiras": "Dirigió durante treinta años una expedición que recorrió las selvas del Nuevo Reino de Granada para dibujar y describir cada planta que encontraba.",
        "teny": "Su expedición dejó miles de láminas botánicas pintadas a mano, muchas con colores fabricados a partir de las propias plantas.",
        "erdekesseg": "Montó una escuela de pintores del lugar solo para retratar flores: llegaron a trabajar decenas de artistas a la vez.",
        "idezet": "Treinta años dibujando una selva entera, hoja por hoja.",
        "idezet_tipus": "jelmondat",
        "prompt": "Jose Celestino Mutis, powdered white hair, calm lined face, dark 18th-century coat. Studying a large open botanical folio of hand-painted flower plates on a table, pressed plants and glass jars around him, an open window showing green tropical forest. Warm daylight."
    },
    {
        "id": "es_medio_3_elhuyar",
        "sorszam": 3,
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Materia, fuerzas y energía",
        "nev": "Fausto Elhuyar",
        "alnev": "químico y mineralogista · 1755–1833",
        "kep": "medio_3_elhuyar",
        "ritkasag": "nagyon_ritka",
        "ero": 400,
        "kepesseg": "Wolframio",
        "kepesseg_ero": 330,
        "becenev": "EL QUE SACÓ UN METAL DE LA PIEDRA",
        "leiras": "Junto a su hermano Juan José consiguió aislar por primera vez el wolframio, el metal que aguanta más calor sin fundirse.",
        "teny": "Lo lograron en 1783, en Bergara. Es el único elemento químico aislado por primera vez en España.",
        "erdekesseg": "El wolframio se funde a más de tres mil cuatrocientos grados. Por eso durante cien años fue el hilo que brillaba dentro de las bombillas.",
        "idezet": "1783, Bergara: de una piedra oscura salió el metal más duro de fundir.",
        "idezet_tipus": "jelmondat",
        "prompt": "Fausto Elhuyar, young serious face, tied-back powdered hair, dark coat with rolled sleeves and a leather apron. Lifting a glowing crucible from a stone furnace beside a dark chunk of wolframite ore, bellows and assay balances around him. Orange furnace glow against cold stone walls."
    },
    {
        "id": "es_medio_3_peral",
        "sorszam": 4,
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Materia, fuerzas y energía",
        "nev": "Isaac Peral",
        "alnev": "marino e ingeniero · 1851–1895",
        "kep": "medio_3_peral",
        "ritkasag": "ritka",
        "ero": 340,
        "kepesseg": "Submarino eléctrico",
        "kepesseg_ero": 280,
        "becenev": "EL QUE BAJÓ AL FONDO",
        "leiras": "Construyó un submarino movido solo por electricidad, capaz de navegar sumergido, orientarse y lanzar un torpedo.",
        "teny": "Se botó en Cádiz en 1888 y funcionó. Aun así, la Marina acabó cancelando el proyecto y el submarino quedó abandonado en el puerto.",
        "erdekesseg": "Para saber dónde estaba bajo el agua inventó un aparato propio que le permitía ver la superficie sin salir a ella.",
        "idezet": "Funcionaba. Y aun así lo dejaron en el muelle.",
        "idezet_tipus": "jelmondat",
        "prompt": "Isaac Peral, dark hair, full dark beard, 19th-century Spanish naval officer uniform with braid. Standing on a stone quay beside a riveted iron submarine with a small conning tower floating in the water, coiled ropes and gas lamps on the dock. Grey Atlantic dawn light."
    },
    {
        "id": "es_medio_3_cabrera",
        "sorszam": 5,
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Materia, fuerzas y energía",
        "nev": "Blas Cabrera",
        "alnev": "físico · 1878–1945",
        "kep": "medio_3_cabrera",
        "ritkasag": "ritka",
        "ero": 330,
        "kepesseg": "Magnetismo",
        "kepesseg_ero": 270,
        "becenev": "EL QUE MIDIÓ LO INVISIBLE",
        "leiras": "Midió con una precisión enorme cómo responden los materiales al imán, y sus datos se usaron en laboratorios de toda Europa.",
        "teny": "Fue el físico español más reconocido de su tiempo y formó parte del comité internacional que decide cuánto mide un metro y cuánto pesa un kilo.",
        "erdekesseg": "Cuando Einstein visitó España en 1923, fue Blas Cabrera quien le acompañó y quien tradujo sus conferencias.",
        "idezet": "Lo que no se puede ver, se puede medir.",
        "idezet_tipus": "jelmondat",
        "prompt": "Blas Cabrera, short dark hair, round glasses, neat moustache, dark three-piece suit. Adjusting a large brass electromagnet with copper coils on a laboratory bench, galvanometers and mirror scales around him. Cool blue-white light in an early-20th-century physics laboratory."
    },
    {
        "id": "es_medio_3_torres",
        "sorszam": 6,
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Proyectos de diseño y pensamiento computacional",
        "nev": "Leonardo Torres Quevedo",
        "alnev": "ingeniero e inventor · 1852–1936",
        "kep": "medio_3_torres",
        "ritkasag": "nagyon_ritka",
        "ero": 440,
        "kepesseg": "Automática",
        "kepesseg_ero": 370,
        "becenev": "EL PADRE DE LOS AUTÓMATAS",
        "leiras": "Construyó máquinas que decidían solas qué hacer, mucho antes de que existieran los ordenadores. También inventó el mando a distancia.",
        "teny": "En 1912 presentó El Ajedrecista, una máquina que jugaba de verdad un final de ajedrez contra una persona y ganaba siempre, sin que nadie la manejara.",
        "erdekesseg": "Diseñó el teleférico que cruza el remolino del Niágara. Se abrió en 1916 y más de cien años después sigue llevando pasajeros.",
        "idezet": "Una máquina que piensa el final de la partida, en 1912.",
        "idezet_tipus": "jelmondat",
        "prompt": "Leonardo Torres Quevedo, white hair, thick white moustache, dark early-1900s suit. Standing beside a wooden chess automaton cabinet with a chessboard on top and exposed brass gears inside, technical drawings and cable-car models on the walls. Warm workshop light."
    },
    {
        "id": "es_medio_3_elcano",
        "sorszam": 7,
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sociedades en el tiempo",
        "nev": "Juan Sebastián Elcano",
        "alnev": "marino · 1476–1526",
        "kep": "medio_3_elcano",
        "ritkasag": "legendas",
        "ero": 480,
        "kepesseg": "La primera vuelta al mundo",
        "kepesseg_ero": 400,
        "becenev": "EL PRIMERO EN DAR LA VUELTA",
        "leiras": "Completó el primer viaje alrededor de la Tierra. Salió con cinco barcos y volvió con uno solo, tres años después.",
        "teny": "De los más de doscientos hombres que salieron, apenas dieciocho regresaron a bordo de la nao Victoria en 1522.",
        "erdekesseg": "El emperador le concedió un escudo con un globo terráqueo y una frase en latín: Primus circumdedisti me, «el primero que me rodeaste».",
        "idezet": "Primus circumdedisti me.",
        "idezet_tipus": "idezet",
        "prompt": "Juan Sebastian Elcano, weathered sunburnt face, short dark beard, 16th-century sailor's coat and cap. On the deck of a battered wooden caravel with torn sails, a large brass globe on the rail beside him, ropes and empty water barrels. Open ocean and low golden light."
    },
    {
        "id": "es_medio_3_alfonsox",
        "sorszam": 8,
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sociedades en el tiempo",
        "nev": "Alfonso X el Sabio",
        "alnev": "rey y erudito · 1221–1284",
        "kep": "medio_3_alfonsox",
        "ritkasag": "nagyon_ritka",
        "ero": 420,
        "kepesseg": "La Escuela de Traductores",
        "kepesseg_ero": 350,
        "becenev": "EL REY QUE HIZO LIBROS",
        "leiras": "Reunió en Toledo a sabios cristianos, musulmanes y judíos para traducir juntos los libros de ciencia que había en árabe, hebreo y latín.",
        "teny": "Ordenó que los libros del reino se escribieran en castellano y no en latín. Por eso el castellano se convirtió en lengua de estudio y no solo de calle.",
        "erdekesseg": "Mandó calcular unas tablas del movimiento de los astros tan buenas que en Europa se usaron durante casi trescientos años.",
        "idezet": "Que se escriba en la lengua que la gente entiende.",
        "idezet_tipus": "jelmondat",
        "prompt": "Alfonso X, crowned middle-aged king, trimmed beard, rich red and gold medieval robes. Seated in a scriptorium before a great illuminated manuscript on a lectern, gold letters and star charts on the page, scribes of different cultures working at desks behind him. Warm candlelight on stone arches."
    },
    {
        "id": "es_medio_3_lascasas",
        "sorszam": 9,
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Alfabetización cívica",
        "nev": "Bartolomé de las Casas",
        "alnev": "fraile y cronista · 1484–1566",
        "kep": "medio_3_lascasas",
        "ritkasag": "ritka",
        "ero": 330,
        "kepesseg": "La denuncia",
        "kepesseg_ero": 270,
        "becenev": "LA VOZ QUE NO CALLÓ",
        "leiras": "Vio de cerca cómo se trataba a los pueblos indígenas de América y dedicó el resto de su vida a denunciarlo delante del rey.",
        "teny": "Escribió un libro entero, la Brevísima relación, contando lo que había visto. Se tradujo por toda Europa y provocó un escándalo enorme.",
        "erdekesseg": "Al principio él mismo tuvo tierras y trabajadores a su cargo. Renunció a todo cuando entendió que aquello no podía defenderse.",
        "idezet": "Todos son hombres, y todos tienen los mismos derechos.",
        "idezet_tipus": "jelmondat",
        "prompt": "Bartolome de las Casas, elderly gaunt face, white beard, tonsure, plain grey Dominican habit. Standing at a table with a heavy open chronicle and a quill resting on the page, a barred window with harsh tropical light outside. Sober muted colours."
    },
    {
        "id": "es_matematicas_3_juarismi",
        "sorszam": 10,
        "oldal": "es",
        "targy": "Matemáticas",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sentido algebraico",
        "nev": "Al-Juarismi",
        "alnev": "matemático · h. 780–850",
        "kep": "matematicas_3_juarismi",
        "ritkasag": "legendas",
        "ero": 470,
        "kepesseg": "Álgebra",
        "kepesseg_ero": 390,
        "becenev": "EL ORIGEN DE LA PALABRA",
        "leiras": "Escribió el libro que enseñó a resolver problemas con incógnitas, es decir, con letras en lugar de números conocidos.",
        "teny": "De su libro salió la palabra álgebra, y de su propio nombre salió la palabra algoritmo. Las dos se usan hoy en todo el mundo.",
        "erdekesseg": "También explicó cómo escribir los números con las cifras del 0 al 9 que usamos hoy, en lugar de con letras romanas.",
        "idezet": "Del título de un libro salió el álgebra; de un nombre, el algoritmo.",
        "idezet_tipus": "jelmondat",
        "prompt": "Al-Khwarizmi, dignified bearded scholar in a green and cream robe and turban. Seated on cushions before a large open manuscript covered in Arabic geometric diagrams and calculations, shelves of scrolls and an astrolabe beside him. Warm desert daylight through a carved screen."
    },
    {
        "id": "es_matematicas_3_azarquiel",
        "sorszam": 11,
        "oldal": "es",
        "targy": "Matemáticas",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sentido de la medida",
        "nev": "Azarquiel",
        "alnev": "astrónomo de Toledo · 1029–1087",
        "kep": "matematicas_3_azarquiel",
        "ritkasag": "nagyon_ritka",
        "ero": 410,
        "kepesseg": "La azafea",
        "kepesseg_ero": 340,
        "becenev": "EL RELOJERO DE LAS ESTRELLAS",
        "leiras": "Construyó un astrolabio que servía en cualquier lugar del mundo, no solo en la ciudad para la que estaba hecho.",
        "teny": "Sus tablas del movimiento de los astros, calculadas en Toledo, se copiaron y se usaron por toda Europa durante siglos.",
        "erdekesseg": "Empezó como artesano fabricando instrumentos para otros astrónomos. Aprendió mirándolos trabajar, hasta que los superó.",
        "idezet": "Un instrumento que funciona en cualquier punto de la Tierra.",
        "idezet_tipus": "jelmondat",
        "prompt": "Azarquiel, bearded man in an ochre robe and turban. Holding a large engraved brass astrolabe upright on the stone parapet of a rooftop terrace in medieval Toledo at night, engraving tools and charts beside him. Star-filled sky, dark city roofs, deep blue and warm lamp light."
    },
    {
        "id": "es_matematicas_3_jorgejuan",
        "sorszam": 12,
        "oldal": "es",
        "targy": "Matemáticas",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sentido de la medida",
        "nev": "Jorge Juan",
        "alnev": "marino y científico · 1713–1773",
        "kep": "matematicas_3_jorgejuan",
        "ritkasag": "ritka",
        "ero": 340,
        "kepesseg": "El meridiano",
        "kepesseg_ero": 280,
        "becenev": "EL QUE MIDIÓ LA TIERRA",
        "leiras": "Viajó hasta el ecuador para medir cuánto mide un grado del meridiano y averiguar así la forma exacta de la Tierra.",
        "teny": "La expedición duró casi diez años. El resultado confirmó que la Tierra no es una bola perfecta: está achatada por los polos.",
        "erdekesseg": "En aquel viaje él y su compañero Antonio de Ulloa describieron por primera vez para la ciencia europea un metal nuevo: el platino.",
        "idezet": "Casi diez años de viaje para medir un solo grado.",
        "idezet_tipus": "jelmondat",
        "prompt": "Jorge Juan, young officer in an 18th-century Spanish naval coat and tricorn hat. Sighting through a large brass quadrant on a tripod on a high Andean ridge, measuring chains and a survey notebook beside him. Snow-capped mountains, clear pale light."
    },
    {
        "id": "es_matematicas_3_hipatia",
        "sorszam": 13,
        "oldal": "es",
        "targy": "Matemáticas",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sentido espacial",
        "nev": "Hipatia de Alejandría",
        "alnev": "matemática y astrónoma · h. 355–415",
        "kep": "matematicas_3_hipatia",
        "ritkasag": "nagyon_ritka",
        "ero": 400,
        "kepesseg": "Astrolabio",
        "kepesseg_ero": 330,
        "becenev": "LA MAESTRA DE ALEJANDRÍA",
        "leiras": "Enseñaba matemáticas y astronomía en Alejandría, y alumnos de todo el Mediterráneo viajaban hasta allí para escucharla.",
        "teny": "Preparó ediciones comentadas de los grandes libros de matemáticas de su época para que se pudieran seguir estudiando.",
        "erdekesseg": "Un alumno suyo le escribió cartas pidiéndole instrucciones para construir instrumentos de medida. Esas cartas se conservan.",
        "idezet": "Enseñó cuando casi ninguna mujer podía hacerlo.",
        "idezet_tipus": "jelmondat",
        "prompt": "Hypatia of Alexandria, calm woman with dark hair gathered under a pale headband, simple white and blue draped robes. Holding a bronze astrolabe over a marble table of papyrus scrolls, geometric figures drawn on a wax board beside her, columns behind. Bright Mediterranean light."
    },
    {
        "id": "es_matematicas_2_firnas",
        "sorszam": 14,
        "oldal": "es",
        "targy": "Matemáticas",
        "ciklus": 2,
        "evfolyam": 4,
        "evfolyamok": [
            3,
            4
        ],
        "lecke": "Sentido espacial",
        "nev": "Abbás Ibn Firnás",
        "alnev": "inventor de Córdoba · 810–887",
        "kep": "matematicas_2_firnas",
        "ritkasag": "ritka",
        "ero": 330,
        "kepesseg": "El vuelo",
        "kepesseg_ero": 270,
        "becenev": "EL QUE QUISO VOLAR",
        "leiras": "Se fabricó unas alas y se lanzó desde una altura para intentar volar. Planeó un rato de verdad, aunque el aterrizaje salió mal.",
        "teny": "Cuenta la tradición que él mismo dijo después que le había faltado una cola, porque los pájaros frenan con ella al posarse.",
        "erdekesseg": "También montó en su casa una sala que imitaba el cielo, con estrellas, nubes y hasta truenos, para enseñar astronomía.",
        "idezet": "Le faltó la cola, no las ganas.",
        "idezet_tipus": "jelmondat",
        "prompt": "Abbas Ibn Firnas, older bearded man in a light ochre robe and turban. Standing at the edge of a stone rooftop with a large pair of feathered wooden wings strapped to a frame beside him, the city of Cordoba and the river far below. Warm morning light and a strong wind."
    },
    {
        "id": "es_lengua_3_cervantes",
        "sorszam": 15,
        "oldal": "es",
        "targy": "Lengua Castellana y Literatura",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Educación literaria",
        "nev": "Miguel de Cervantes",
        "alnev": "escritor · 1547–1616",
        "kep": "lengua_3_cervantes",
        "ritkasag": "legendas",
        "ero": 480,
        "kepesseg": "Don Quijote",
        "kepesseg_ero": 400,
        "becenev": "EL INVENTOR DE LA NOVELA",
        "leiras": "Escribió Don Quijote, el libro más traducido del mundo después de la Biblia, y con él inventó la novela tal como la leemos hoy.",
        "teny": "Estuvo cinco años cautivo en Argel. Intentó escaparse cuatro veces y nunca delató a ninguno de sus compañeros.",
        "erdekesseg": "Perdió el uso de la mano izquierda en la batalla de Lepanto. Decía que la había perdido «para mayor gloria de la derecha».",
        "idezet": "La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.",
        "idezet_tipus": "idezet",
        "prompt": "Miguel de Cervantes, lean older face, pointed grey beard, high forehead, dark doublet with a white ruff collar. Seated at a worn wooden table with a stack of books and a quill in an inkwell, his left hand resting still in his lap. Candlelight and deep shadow in a bare 17th-century room."
    },
    {
        "id": "es_lengua_3_nebrija",
        "sorszam": 16,
        "oldal": "es",
        "targy": "Lengua Castellana y Literatura",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Las lenguas y sus hablantes",
        "nev": "Elio Antonio de Nebrija",
        "alnev": "gramático · 1444–1522",
        "kep": "lengua_3_nebrija",
        "ritkasag": "nagyon_ritka",
        "ero": 420,
        "kepesseg": "La gramática",
        "kepesseg_ero": 350,
        "becenev": "EL QUE PUSO REGLAS",
        "leiras": "Escribió las primeras reglas del castellano: cómo se ordenan las palabras, cómo se escriben, por qué una frase suena bien.",
        "teny": "Su Gramática se publicó en 1492 y fue la primera gramática escrita de una lengua europea moderna. Hasta entonces solo se hacía con el latín.",
        "erdekesseg": "Cuando le preguntaron para qué servía aquello, contestó que la lengua siempre había acompañado al poder de un reino.",
        "idezet": "Siempre la lengua fue compañera del imperio.",
        "idezet_tipus": "idezet",
        "prompt": "Elio Antonio de Nebrija, older scholar, lined face, dark scholar's cap and gown. Standing at a lectern with a printed grammar book open on it, a printing press behind him, trays of metal type and freshly printed sheets hanging to dry. Warm lamplight."
    },
    {
        "id": "es_lengua_3_lorca",
        "sorszam": 17,
        "oldal": "es",
        "targy": "Lengua Castellana y Literatura",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Educación literaria",
        "nev": "Federico García Lorca",
        "alnev": "poeta y dramaturgo · 1898–1936",
        "kep": "lengua_3_lorca",
        "ritkasag": "nagyon_ritka",
        "ero": 410,
        "kepesseg": "La Barraca",
        "kepesseg_ero": 340,
        "becenev": "EL QUE LLEVÓ EL TEATRO AL PUEBLO",
        "leiras": "Escribió poemas y obras de teatro con el ritmo del habla popular andaluza, y consiguió que sonaran modernos y antiguos a la vez.",
        "teny": "Montó un teatro ambulante, La Barraca, y se recorrió los pueblos de España en camión representando obras clásicas gratis.",
        "erdekesseg": "Era muy buen pianista. Antes de dedicarse a escribir, recogió y armonizó canciones populares antiguas para que no se perdieran.",
        "idezet": "El teatro es la poesía que se levanta del libro y se hace humana.",
        "idezet_tipus": "idezet",
        "prompt": "Federico Garcia Lorca, young man, dark hair, thick eyebrows, broad open face, plain blue workman's overall over a shirt. Beside a small wooden travelling stage on the back of an old truck with painted backdrops and a guitar leaning against it, villagers gathering in a village square. Bright dusty afternoon light."
    },
    {
        "id": "es_lengua_2_rosalia",
        "sorszam": 18,
        "oldal": "es",
        "targy": "Lengua Castellana y Literatura",
        "ciklus": 2,
        "evfolyam": 4,
        "evfolyamok": [
            3,
            4
        ],
        "lecke": "Educación literaria",
        "nev": "Rosalía de Castro",
        "alnev": "poeta · 1837–1885",
        "kep": "lengua_2_rosalia",
        "ritkasag": "ritka",
        "ero": 330,
        "kepesseg": "Cantares gallegos",
        "kepesseg_ero": 270,
        "becenev": "LA VOZ DE GALICIA",
        "leiras": "Escribió poemas en gallego cuando casi nadie publicaba en esa lengua, y consiguió que volviera a considerarse una lengua de literatura.",
        "teny": "Su libro Cantares gallegos se publicó el 17 de mayo de 1863. Por eso Galicia celebra cada 17 de mayo el Día das Letras Galegas.",
        "erdekesseg": "Escribió mucho sobre los que se marchaban a trabajar fuera y sobre los que se quedaban esperando en el pueblo.",
        "idezet": "Adiós ríos, adiós fontes.",
        "idezet_tipus": "idezet",
        "prompt": "Rosalia de Castro, serious young woman, dark hair parted in the middle, dark 19th-century dress with a lace collar. Seated by the window of a Galician stone house with an open handwritten poetry notebook and a black shawl on the sill, green rainy hills outside. Soft grey northern light."
    },
    {
        "id": "es_lengua_3_sorjuana",
        "sorszam": 19,
        "oldal": "es",
        "targy": "Lengua Castellana y Literatura",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Educación literaria",
        "nev": "Sor Juana Inés de la Cruz",
        "alnev": "poeta y pensadora · 1648–1695",
        "kep": "lengua_3_sorjuana",
        "ritkasag": "nagyon_ritka",
        "ero": 400,
        "kepesseg": "La biblioteca",
        "kepesseg_ero": 330,
        "becenev": "LA DÉCIMA MUSA",
        "leiras": "Fue la escritora más admirada de su tiempo en toda América y España, y defendió por escrito que las mujeres tenían derecho a estudiar.",
        "teny": "Reunió en su celda una biblioteca de miles de libros, además de instrumentos musicales y aparatos científicos.",
        "erdekesseg": "De niña pidió que la vistieran de chico para poder entrar en la universidad, porque a las chicas no se les permitía.",
        "idezet": "Hombres necios que acusáis a la mujer sin razón.",
        "idezet_tipus": "idezet",
        "prompt": "Sor Juana Ines de la Cruz, young woman with a calm direct gaze, white nun's habit with a large round medallion on the chest and a black veil. Seated at a writing desk with a quill, tall shelves of leather books and a globe behind her. Warm candlelight on colonial tiled walls."
    },
    {
        "id": "es_artistica_3_velazquez",
        "sorszam": 20,
        "oldal": "es",
        "targy": "Educación Artística",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Artes plásticas, visuales y audiovisuales",
        "nev": "Diego Velázquez",
        "alnev": "pintor · 1599–1660",
        "kep": "artistica_3_velazquez",
        "ritkasag": "legendas",
        "ero": 470,
        "kepesseg": "Las Meninas",
        "kepesseg_ero": 390,
        "becenev": "EL PINTOR DEL REY",
        "leiras": "Pintó la luz y el aire como nadie lo había hecho antes: de cerca son manchas sueltas, y de lejos parece una fotografía.",
        "teny": "En Las Meninas se pintó a sí mismo trabajando dentro del propio cuadro, mirando de frente al que lo está mirando.",
        "erdekesseg": "Fue pintor del rey durante casi cuarenta años, y buena parte de su trabajo consistía en organizar las salas y las fiestas del palacio.",
        "idezet": "De cerca, manchas. De lejos, el aire.",
        "idezet_tipus": "jelmondat",
        "prompt": "Diego Velazquez, dark curled hair, upturned moustache, black 17th-century doublet with a white collar. Standing before a huge canvas on a wooden easel with a loaded palette and long brushes in hand, a tall shadowed palace room with a distant mirror. Cool silvery daylight."
    },
    {
        "id": "es_artistica_3_goya",
        "sorszam": 21,
        "oldal": "es",
        "targy": "Educación Artística",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Artes plásticas, visuales y audiovisuales",
        "nev": "Francisco de Goya",
        "alnev": "pintor y grabador · 1746–1828",
        "kep": "artistica_3_goya",
        "ritkasag": "nagyon_ritka",
        "ero": 430,
        "kepesseg": "Pinturas negras",
        "kepesseg_ero": 360,
        "becenev": "EL QUE PINTÓ LO QUE VIO",
        "leiras": "Empezó pintando fiestas alegres para la corte y acabó pintando la guerra y el miedo tal como eran, sin adornarlos.",
        "teny": "Una enfermedad le dejó sordo a los cuarenta y seis años. A partir de ahí su pintura se volvió mucho más oscura y mucho más libre.",
        "erdekesseg": "Ya mayor pintó una serie de cuadros directamente sobre las paredes de su casa, sin encargo y sin pensar en venderlos.",
        "idezet": "El sueño de la razón produce monstruos.",
        "idezet_tipus": "idezet",
        "prompt": "Francisco de Goya, older man, wild grey hair, heavy brows, stubborn stare, dark coat with a loose neckcloth. At a workbench with a copper etching plate and a burin, beside a wall half-covered with a dark unfinished mural. Oil lamp light and deep brown shadow."
    },
    {
        "id": "es_artistica_2_sorolla",
        "sorszam": 22,
        "oldal": "es",
        "targy": "Educación Artística",
        "ciklus": 2,
        "evfolyam": 4,
        "evfolyamok": [
            3,
            4
        ],
        "lecke": "Artes plásticas, visuales y audiovisuales",
        "nev": "Joaquín Sorolla",
        "alnev": "pintor · 1863–1923",
        "kep": "artistica_2_sorolla",
        "ritkasag": "ritka",
        "ero": 340,
        "kepesseg": "La luz",
        "kepesseg_ero": 280,
        "becenev": "EL PINTOR DE LA LUZ",
        "leiras": "Sacó el caballete a la playa y pintó al aire libre el sol sobre el agua, la ropa mojada y la arena caliente.",
        "teny": "Pasó ocho años pintando catorce paneles enormes con escenas de todas las regiones de España, y viajó a cada una para pintarla allí mismo.",
        "erdekesseg": "Pintaba muy rápido y de pie, porque decía que la luz cambia y no espera a nadie.",
        "idezet": "La luz cambia mientras la miras: hay que pintar deprisa.",
        "idezet_tipus": "jelmondat",
        "prompt": "Joaquin Sorolla, middle-aged man, dark moustache, straw hat, white shirt with rolled sleeves. Painting at a wooden easel planted in wet sand, a bright half-finished beach painting on it and a palette of white and blue in his hand, sea foam and children in the distance. Dazzling Mediterranean midday light."
    },
    {
        "id": "es_artistica_3_falla",
        "sorszam": 23,
        "oldal": "es",
        "targy": "Educación Artística",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Música y artes escénicas y performativas",
        "nev": "Manuel de Falla",
        "alnev": "compositor · 1876–1946",
        "kep": "artistica_3_falla",
        "ritkasag": "ritka",
        "ero": 350,
        "kepesseg": "El amor brujo",
        "kepesseg_ero": 290,
        "becenev": "EL QUE ESCRIBIÓ EL FUEGO",
        "leiras": "Convirtió el flamenco y la música popular andaluza en música de orquesta, sin quitarle la fuerza que tenía.",
        "teny": "Su Danza ritual del fuego, de El amor brujo, es una de las piezas españolas más tocadas del mundo.",
        "erdekesseg": "Organizó en Granada, junto con Lorca, un concurso para rescatar el cante jondo antiguo antes de que se perdiera.",
        "idezet": "La música popular no se copia: se escucha y se sigue.",
        "idezet_tipus": "jelmondat",
        "prompt": "Manuel de Falla, small thin man, bald head, sharp features, dark suit. Seated at a piano in a Granada house with a hand-written orchestral score on the music stand and a guitar leaning against the instrument, whitewashed walls and a window onto a garden with cypresses. Warm southern evening light."
    },
    {
        "id": "es_artistica_2_albeniz",
        "sorszam": 24,
        "oldal": "es",
        "targy": "Educación Artística",
        "ciklus": 2,
        "evfolyam": 4,
        "evfolyamok": [
            3,
            4
        ],
        "lecke": "Música y artes escénicas y performativas",
        "nev": "Isaac Albéniz",
        "alnev": "compositor y pianista · 1860–1909",
        "kep": "artistica_2_albeniz",
        "ritkasag": "ritka",
        "ero": 320,
        "kepesseg": "Iberia",
        "kepesseg_ero": 260,
        "becenev": "EL NIÑO DEL PIANO",
        "leiras": "Escribió para piano piezas que suenan a guitarra española, a fiesta y a calle, y que hoy tocan pianistas de todo el mundo.",
        "teny": "Su obra Iberia son doce piezas tan difíciles que él mismo dudó de si alguien podría tocarlas.",
        "erdekesseg": "Era un niño prodigio y daba conciertos siendo muy pequeño. De mayor le encantaba contar historias exageradas sobre sus viajes de infancia.",
        "idezet": "Doce piezas que casi nadie podía tocar.",
        "idezet_tipus": "jelmondat",
        "prompt": "Isaac Albeniz, stout man, thick dark moustache, genial face, dark late-19th-century suit. Seated at an open grand piano with hand-written sheet music on the stand and a Spanish guitar propped against its leg, heavy curtains behind him. Golden lamplight."
    },
    {
        "id": "es_efisica_3_coubertin",
        "sorszam": 25,
        "oldal": "es",
        "targy": "Educación Física",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Manifestaciones de la cultura motriz",
        "nev": "Pierre de Coubertin",
        "alnev": "pedagogo · 1863–1937",
        "kep": "efisica_3_coubertin",
        "ritkasag": "ritka",
        "ero": 330,
        "kepesseg": "Los Juegos",
        "kepesseg_ero": 270,
        "becenev": "EL QUE VOLVIÓ A ENCENDER LA LLAMA",
        "leiras": "Convenció a media Europa de recuperar los Juegos Olímpicos después de mil quinientos años sin celebrarse.",
        "teny": "Los primeros Juegos modernos se celebraron en Atenas en 1896, dos años después de que él fundara el Comité Olímpico Internacional.",
        "erdekesseg": "Hizo famosa la frase de que lo importante no es ganar sino participar, aunque no fue él quien la dijo primero: la escuchó en un sermón.",
        "idezet": "Lo importante no es ganar, sino participar.",
        "idezet_tipus": "idezet",
        "prompt": "Pierre de Coubertin, small man with a very large dark moustache, formal 1890s suit and hat. Standing in Olympia before ancient stadium ruins with a laurel wreath and an unrolled olympic charter on a stone bench beside him, marble columns and dry grass. Clear Greek morning light."
    },
    {
        "id": "es_extranjera_3_battuta",
        "sorszam": 26,
        "oldal": "es",
        "targy": "Lengua Extranjera",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Interculturalidad",
        "nev": "Ibn Battuta",
        "alnev": "viajero y cronista · 1304–1368",
        "kep": "extranjera_3_battuta",
        "ritkasag": "nagyon_ritka",
        "ero": 400,
        "kepesseg": "La Rihla",
        "kepesseg_ero": 330,
        "becenev": "EL QUE NO PARABA",
        "leiras": "Se pasó veintinueve años viajando y recorrió unos ciento veinte mil kilómetros, mucho más que ningún otro viajero de su época.",
        "teny": "A la vuelta le dictó todo a un escribano. Ese libro, la Rihla, cuenta cómo se comía, se rezaba y se hablaba en decenas de países.",
        "erdekesseg": "Salió de casa a los veintiún años pensando en hacer un solo viaje. Volvió con el pelo gris.",
        "idezet": "Salí solo, sin compañero de viaje y sin caravana.",
        "idezet_tipus": "idezet",
        "prompt": "Ibn Battuta, bearded traveller in a dusty cream robe and turban. Standing at a caravanserai gate beside a worn leather travel satchel, a rolled map and a walking staff resting against the stone wall, camels and a busy market street behind him. Warm dusty afternoon light."
    }
]
