# -*- coding: utf-8 -*-
"""TutorIA – a spanyol oldal kártyái (LOMLOE, 1–6. Primaria).

Bekötés a kartyak.py végén:
    from kartyak_es import KARTYAK_ES
    KARTYAK.extend(KARTYAK_ES)
"""

KARTYAK_ES: list[dict] = [
    {
        "id": "es_medio_3_cajal",
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Iniciación en la actividad científica",
        "nev": "Santiago Ramón y Cajal",
        "alnev": "médico e investigador · 1852–1934",
        "kep": "medio_3_cajal",
        "ritkasag": "nagyon_ritka",
        "ero": 450,
        "kepesseg": "Neuronas",
        "kepesseg_ero": 380,
        "becenev": "EL DIBUJANTE DEL CEREBRO",
        "leiras": "Demostró que el cerebro no es una red continua, sino millones de células separadas que se hablan entre sí. Por eso recibió el Premio Nobel en 1906.",
        "teny": "Dibujó a mano miles de láminas de neuronas mientras miraba por el microscopio. Todavía hoy se usan en las facultades de medicina de todo el mundo.",
        "erdekesseg": "De niño quería ser pintor y su padre no se lo permitió. Al final fue su mano de dibujante la que le hizo famoso.",
        "idezet": "Todo hombre puede ser, si se lo propone, escultor de su propio cerebro.",
        "idezet_tipus": "idezet",
        "prompt": "a brass microscope on a wooden desk with a glass slide under it, and beside it Santiago Ramon y Cajal seated in his study, the person's face fully visible and unobstructed, the microscope beside him not covering the face, balding head with a short grey beard and deep-set intense eyes, dark late-19th-century jacket and waistcoat, his own ink drawings of branching neurons pinned on the wall behind him and spread on the desk, warm lamplight and deep shadow"
    },
    {
        "id": "es_medio_2_mutis",
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 2,
        "evfolyam": 4,
        "evfolyamok": [
            3,
            4
        ],
        "lecke": "La vida en nuestro planeta",
        "nev": "José Celestino Mutis",
        "alnev": "médico y botánico · 1732–1808",
        "kep": "medio_2_mutis",
        "ritkasag": "ritka",
        "ero": 320,
        "kepesseg": "Expedición botánica",
        "kepesseg_ero": 260,
        "becenev": "EL CAZADOR DE PLANTAS",
        "leiras": "Dirigió durante treinta años una expedición que recorrió las selvas del Nuevo Reino de Granada para dibujar y describir cada planta que encontraba.",
        "teny": "Su expedición dejó miles de láminas botánicas pintadas a mano, muchas con colores fabricados a partir de las propias plantas.",
        "erdekesseg": "Montó una escuela de pintores del lugar solo para retratar flores: llegaron a trabajar decenas de artistas a la vez.",
        "idezet": "Treinta años dibujando una selva entera, hoja por hoja.",
        "idezet_tipus": "jelmondat",
        "prompt": "a large open botanical folio with a hand-painted flower plate on a table, and beside it Jose Celestino Mutis standing in a colonial study, the person's face fully visible and unobstructed, the folio beside him not covering the face, powdered white hair and a calm lined face, dark 18th-century coat, pressed plants and glass jars around him, an open window showing green tropical forest, warm daylight"
    },
    {
        "id": "es_medio_3_elhuyar",
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Materia, fuerzas y energía",
        "nev": "Fausto Elhuyar",
        "alnev": "químico y mineralogista · 1755–1833",
        "kep": "medio_3_elhuyar",
        "ritkasag": "nagyon_ritka",
        "ero": 400,
        "kepesseg": "Wolframio",
        "kepesseg_ero": 330,
        "becenev": "EL QUE SACÓ UN METAL DE LA PIEDRA",
        "leiras": "Junto a su hermano Juan José consiguió aislar por primera vez el wolframio, el metal que aguanta más calor sin fundirse.",
        "teny": "Lo lograron en 1783, en Bergara. Es el único elemento químico aislado por primera vez en España.",
        "erdekesseg": "El wolframio se funde a más de tres mil cuatrocientos grados. Por eso durante cien años fue el hilo que brillaba dentro de las bombillas.",
        "idezet": "1783, Bergara: de una piedra oscura salió el metal más duro de fundir.",
        "idezet_tipus": "jelmondat",
        "prompt": "a dark chunk of wolframite ore and a glowing crucible on a stone furnace bench, and beside them Fausto Elhuyar in an 18th-century laboratory, the person's face fully visible and unobstructed, the crucible beside him not covering the face, tied-back powdered hair and a young serious face, dark coat with rolled sleeves and a leather apron, bellows and assay balances around him, orange furnace glow against cold stone walls"
    },
    {
        "id": "es_medio_3_peral",
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Materia, fuerzas y energía",
        "nev": "Isaac Peral",
        "alnev": "marino e ingeniero · 1851–1895",
        "kep": "medio_3_peral",
        "ritkasag": "ritka",
        "ero": 340,
        "kepesseg": "Submarino eléctrico",
        "kepesseg_ero": 280,
        "becenev": "EL QUE BAJÓ AL FONDO",
        "leiras": "Construyó un submarino movido solo por electricidad, capaz de navegar sumergido, orientarse y lanzar un torpedo.",
        "teny": "Se botó en Cádiz en 1888 y funcionó. Aun así, la Marina acabó cancelando el proyecto y el submarino quedó abandonado en el puerto.",
        "erdekesseg": "Para saber dónde estaba bajo el agua inventó un aparato propio que le permitía ver la superficie sin salir a ella.",
        "idezet": "Funcionaba. Y aun así lo dejaron en el muelle.",
        "idezet_tipus": "jelmondat",
        "prompt": "a riveted iron submarine hull with a small conning tower floating at a stone dock, and beside it Isaac Peral standing on the quay, the person's face fully visible and unobstructed, the submarine behind him not covering the face, dark hair and a full dark beard, 19th-century Spanish naval officer uniform with braid, coiled ropes and gas lamps on the dock, grey Atlantic dawn light"
    },
    {
        "id": "es_medio_3_cabrera",
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Materia, fuerzas y energía",
        "nev": "Blas Cabrera",
        "alnev": "físico · 1878–1945",
        "kep": "medio_3_cabrera",
        "ritkasag": "ritka",
        "ero": 330,
        "kepesseg": "Magnetismo",
        "kepesseg_ero": 270,
        "becenev": "EL QUE MIDIÓ LO INVISIBLE",
        "leiras": "Midió con una precisión enorme cómo responden los materiales al imán, y sus datos se usaron en laboratorios de toda Europa.",
        "teny": "Fue el físico español más reconocido de su tiempo y formó parte del comité internacional que decide cuánto mide un metro y cuánto pesa un kilo.",
        "erdekesseg": "Cuando Einstein visitó España en 1923, fue Blas Cabrera quien le acompañó y quien tradujo sus conferencias.",
        "idezet": "Lo que no se puede ver, se puede medir.",
        "idezet_tipus": "jelmondat",
        "prompt": "a large brass electromagnet with copper coils on a laboratory bench, and beside it Blas Cabrera in an early-20th-century physics laboratory, the person's face fully visible and unobstructed, the electromagnet beside him not covering the face, short dark hair, round glasses and a neat moustache, dark three-piece suit, galvanometers and mirror scales around him, cool blue-white light"
    },
    {
        "id": "es_medio_3_torres",
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Proyectos de diseño y pensamiento computacional",
        "nev": "Leonardo Torres Quevedo",
        "alnev": "ingeniero e inventor · 1852–1936",
        "kep": "medio_3_torres",
        "ritkasag": "nagyon_ritka",
        "ero": 440,
        "kepesseg": "Automática",
        "kepesseg_ero": 370,
        "becenev": "EL PADRE DE LOS AUTÓMATAS",
        "leiras": "Construyó máquinas que decidían solas qué hacer, mucho antes de que existieran los ordenadores. También inventó el mando a distancia.",
        "teny": "En 1912 presentó El Ajedrecista, una máquina que jugaba de verdad un final de ajedrez contra una persona y ganaba siempre, sin que nadie la manejara.",
        "erdekesseg": "Diseñó el teleférico que cruza el remolino del Niágara. Se abrió en 1916 y más de cien años después sigue llevando pasajeros.",
        "idezet": "Una máquina que piensa el final de la partida, en 1912.",
        "idezet_tipus": "jelmondat",
        "prompt": "a wooden chess automaton cabinet with a chessboard on top and exposed brass gears inside, and beside it Leonardo Torres Quevedo in his workshop, the person's face fully visible and unobstructed, the automaton beside him not covering the face, white hair and a thick white moustache, dark early-1900s suit, technical drawings and cable-car models on the walls, warm workshop light"
    },
    {
        "id": "es_medio_3_elcano",
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sociedades en el tiempo",
        "nev": "Juan Sebastián Elcano",
        "alnev": "marino · 1476–1526",
        "kep": "medio_3_elcano",
        "ritkasag": "legendas",
        "ero": 480,
        "kepesseg": "La primera vuelta al mundo",
        "kepesseg_ero": 400,
        "becenev": "EL PRIMERO EN DAR LA VUELTA",
        "leiras": "Completó el primer viaje alrededor de la Tierra. Salió con cinco barcos y volvió con uno solo, tres años después.",
        "teny": "De los más de doscientos hombres que salieron, apenas dieciocho regresaron a bordo de la nao Victoria en 1522.",
        "erdekesseg": "El emperador le concedió un escudo con un globo terráqueo y una frase en latín: Primus circumdedisti me, «el primero que me rodeaste».",
        "idezet": "Primus circumdedisti me.",
        "idezet_tipus": "idezet",
        "prompt": "a battered wooden caravel with torn sails and a large brass globe on the deck rail, and beside them Juan Sebastian Elcano standing at the ship's side, the person's face fully visible and unobstructed, the globe beside him not covering the face, weathered sunburnt face with a short dark beard, 16th-century sailor's coat and cap, ropes and empty water barrels, open ocean and low golden light"
    },
    {
        "id": "es_medio_3_alfonsox",
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sociedades en el tiempo",
        "nev": "Alfonso X el Sabio",
        "alnev": "rey y erudito · 1221–1284",
        "kep": "medio_3_alfonsox",
        "ritkasag": "nagyon_ritka",
        "ero": 420,
        "kepesseg": "La Escuela de Traductores",
        "kepesseg_ero": 350,
        "becenev": "EL REY QUE HIZO LIBROS",
        "leiras": "Reunió en Toledo a sabios cristianos, musulmanes y judíos para traducir juntos los libros de ciencia que había en árabe, hebreo y latín.",
        "teny": "Ordenó que los libros del reino se escribieran en castellano y no en latín. Por eso el castellano se convirtió en lengua de estudio y no solo de calle.",
        "erdekesseg": "Mandó calcular unas tablas del movimiento de los astros tan buenas que en Europa se usaron durante casi trescientos años.",
        "idezet": "Que se escriba en la lengua que la gente entiende.",
        "idezet_tipus": "jelmondat",
        "prompt": "a great illuminated manuscript open on a lectern with gold letters and star charts, and beside it Alfonso X seated in a medieval scriptorium, the person's face fully visible and unobstructed, the manuscript beside him not covering the face, a crowned middle-aged king with a trimmed beard, rich red and gold medieval robes, scribes of different cultures working at desks behind him, warm candlelight on stone arches"
    },
    {
        "id": "es_medio_3_lascasas",
        "oldal": "es",
        "targy": "Conocimiento del Medio Natural, Social y Cultural",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Alfabetización cívica",
        "nev": "Bartolomé de las Casas",
        "alnev": "fraile y cronista · 1484–1566",
        "kep": "medio_3_lascasas",
        "ritkasag": "ritka",
        "ero": 330,
        "kepesseg": "La denuncia",
        "kepesseg_ero": 270,
        "becenev": "LA VOZ QUE NO CALLÓ",
        "leiras": "Vio de cerca cómo se trataba a los pueblos indígenas de América y dedicó el resto de su vida a denunciarlo delante del rey.",
        "teny": "Escribió un libro entero, la Brevísima relación, contando lo que había visto. Se tradujo por toda Europa y provocó un escándalo enorme.",
        "erdekesseg": "Al principio él mismo tuvo tierras y trabajadores a su cargo. Renunció a todo cuando entendió que aquello no podía defenderse.",
        "idezet": "Todos son hombres, y todos tienen los mismos derechos.",
        "idezet_tipus": "jelmondat",
        "prompt": "a heavy open chronicle with a quill resting on the page and a wooden crucifix beside it on a table, and beside them Bartolome de las Casas standing in a bare colonial room, the person's face fully visible and unobstructed, the book beside him not covering the face, an elderly gaunt face with white beard and tonsure, plain grey Dominican habit, a barred window with harsh tropical light outside, sober muted colours"
    },
    {
        "id": "es_matematicas_3_juarismi",
        "oldal": "es",
        "targy": "Matemáticas",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sentido algebraico",
        "nev": "Al-Juarismi",
        "alnev": "matemático · h. 780–850",
        "kep": "matematicas_3_juarismi",
        "ritkasag": "legendas",
        "ero": 470,
        "kepesseg": "Álgebra",
        "kepesseg_ero": 390,
        "becenev": "EL ORIGEN DE LA PALABRA",
        "leiras": "Escribió el libro que enseñó a resolver problemas con incógnitas, es decir, con letras en lugar de números conocidos.",
        "teny": "De su libro salió la palabra álgebra, y de su propio nombre salió la palabra algoritmo. Las dos se usan hoy en todo el mundo.",
        "erdekesseg": "También explicó cómo escribir los números con las cifras del 0 al 9 que usamos hoy, en lugar de con letras romanas.",
        "idezet": "Del título de un libro salió el álgebra; de un nombre, el algoritmo.",
        "idezet_tipus": "jelmondat",
        "prompt": "a large open manuscript covered in Arabic geometric diagrams and calculations on a low table, and beside it Al-Khwarizmi seated on cushions in a 9th-century house of wisdom, the person's face fully visible and unobstructed, the manuscript beside him not covering the face, a dignified bearded scholar in a green and cream robe and turban, shelves of scrolls and an astrolabe, warm desert daylight through a carved screen"
    },
    {
        "id": "es_matematicas_3_azarquiel",
        "oldal": "es",
        "targy": "Matemáticas",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sentido de la medida",
        "nev": "Azarquiel",
        "alnev": "astrónomo de Toledo · 1029–1087",
        "kep": "matematicas_3_azarquiel",
        "ritkasag": "nagyon_ritka",
        "ero": 410,
        "kepesseg": "La azafea",
        "kepesseg_ero": 340,
        "becenev": "EL RELOJERO DE LAS ESTRELLAS",
        "leiras": "Construyó un astrolabio que servía en cualquier lugar del mundo, no solo en la ciudad para la que estaba hecho.",
        "teny": "Sus tablas del movimiento de los astros, calculadas en Toledo, se copiaron y se usaron por toda Europa durante siglos.",
        "erdekesseg": "Empezó como artesano fabricando instrumentos para otros astrónomos. Aprendió mirándolos trabajar, hasta que los superó.",
        "idezet": "Un instrumento que funciona en cualquier punto de la Tierra.",
        "idezet_tipus": "jelmondat",
        "prompt": "a large engraved brass astrolabe held upright on a stone parapet, and beside it Azarquiel standing on a rooftop terrace in medieval Toledo at night, the person's face fully visible and unobstructed, the astrolabe beside him not covering the face, a bearded man in an ochre robe and turban, engraving tools and charts on the parapet, the star-filled sky and dark city roofs behind, deep blue and warm lamp light"
    },
    {
        "id": "es_matematicas_3_jorgejuan",
        "oldal": "es",
        "targy": "Matemáticas",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sentido de la medida",
        "nev": "Jorge Juan",
        "alnev": "marino y científico · 1713–1773",
        "kep": "matematicas_3_jorgejuan",
        "ritkasag": "ritka",
        "ero": 340,
        "kepesseg": "El meridiano",
        "kepesseg_ero": 280,
        "becenev": "EL QUE MIDIÓ LA TIERRA",
        "leiras": "Viajó hasta el ecuador para medir cuánto mide un grado del meridiano y averiguar así la forma exacta de la Tierra.",
        "teny": "La expedición duró casi diez años. El resultado confirmó que la Tierra no es una bola perfecta: está achatada por los polos.",
        "erdekesseg": "En aquel viaje él y su compañero Antonio de Ulloa describieron por primera vez para la ciencia europea un metal nuevo: el platino.",
        "idezet": "Casi diez años de viaje para medir un solo grado.",
        "idezet_tipus": "jelmondat",
        "prompt": "a large brass quadrant instrument on a tripod pointing at the sky, and beside it Jorge Juan standing on a high Andean ridge, the person's face fully visible and unobstructed, the instrument beside him not covering the face, a young officer in an 18th-century Spanish naval coat and tricorn hat, measuring chains and a survey notebook, snow-capped mountains and thin cold air, clear pale light"
    },
    {
        "id": "es_matematicas_3_hipatia",
        "oldal": "es",
        "targy": "Matemáticas",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Sentido espacial",
        "nev": "Hipatia de Alejandría",
        "alnev": "matemática y astrónoma · h. 355–415",
        "kep": "matematicas_3_hipatia",
        "ritkasag": "nagyon_ritka",
        "ero": 400,
        "kepesseg": "Astrolabio",
        "kepesseg_ero": 330,
        "becenev": "LA MAESTRA DE ALEJANDRÍA",
        "leiras": "Enseñaba matemáticas y astronomía en Alejandría, y alumnos de todo el Mediterráneo viajaban hasta allí para escucharla.",
        "teny": "Preparó ediciones comentadas de los grandes libros de matemáticas de su época para que se pudieran seguir estudiando.",
        "erdekesseg": "Un alumno suyo le escribió cartas pidiéndole instrucciones para construir instrumentos de medida. Esas cartas se conservan.",
        "idezet": "Enseñó cuando casi ninguna mujer podía hacerlo.",
        "idezet_tipus": "jelmondat",
        "prompt": "a bronze astrolabe and rolled papyrus scrolls on a marble table, and beside them Hypatia standing in a sunlit Alexandrian hall, the person's face fully visible and unobstructed, the astrolabe beside her not covering the face, a calm woman with dark hair gathered under a pale headband, simple white and blue draped robes, columns and geometric figures drawn on a wax board, bright Mediterranean light"
    },
    {
        "id": "es_matematicas_2_firnas",
        "oldal": "es",
        "targy": "Matemáticas",
        "ciklus": 2,
        "evfolyam": 4,
        "evfolyamok": [
            3,
            4
        ],
        "lecke": "Sentido espacial",
        "nev": "Abbás Ibn Firnás",
        "alnev": "inventor de Córdoba · 810–887",
        "kep": "matematicas_2_firnas",
        "ritkasag": "ritka",
        "ero": 330,
        "kepesseg": "El vuelo",
        "kepesseg_ero": 270,
        "becenev": "EL QUE QUISO VOLAR",
        "leiras": "Se fabricó unas alas y se lanzó desde una altura para intentar volar. Planeó un rato de verdad, aunque el aterrizaje salió mal.",
        "teny": "Cuenta la tradición que él mismo dijo después que le había faltado una cola, porque los pájaros frenan con ella al posarse.",
        "erdekesseg": "También montó en su casa una sala que imitaba el cielo, con estrellas, nubes y hasta truenos, para enseñar astronomía.",
        "idezet": "Le faltó la cola, no las ganas.",
        "idezet_tipus": "jelmondat",
        "prompt": "a large pair of feathered wooden wings strapped to a wooden frame on a stone rooftop, and beside them Abbas Ibn Firnas standing at the edge, the person's face fully visible and unobstructed, the wings beside him not covering the face, an older bearded man in a light ochre robe and turban, the city of Cordoba and the river far below, warm morning light and a strong wind"
    },
    {
        "id": "es_lengua_3_cervantes",
        "oldal": "es",
        "targy": "Lengua Castellana y Literatura",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Educación literaria",
        "nev": "Miguel de Cervantes",
        "alnev": "escritor · 1547–1616",
        "kep": "lengua_3_cervantes",
        "ritkasag": "legendas",
        "ero": 480,
        "kepesseg": "Don Quijote",
        "kepesseg_ero": 400,
        "becenev": "EL INVENTOR DE LA NOVELA",
        "leiras": "Escribió Don Quijote, el libro más traducido del mundo después de la Biblia, y con él inventó la novela tal como la leemos hoy.",
        "teny": "Estuvo cinco años cautivo en Argel. Intentó escaparse cuatro veces y nunca delató a ninguno de sus compañeros.",
        "erdekesseg": "Perdió el uso de la mano izquierda en la batalla de Lepanto. Decía que la había perdido «para mayor gloria de la derecha».",
        "idezet": "La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.",
        "idezet_tipus": "idezet",
        "prompt": "a stack of quarto books and a quill in an inkwell on a worn wooden table, and beside them Miguel de Cervantes seated in a bare 17th-century room, the person's face fully visible and unobstructed, the books beside him not covering the face, a lean older face with a pointed grey beard and high forehead, dark doublet with a white ruff collar, his left hand resting still in his lap, candlelight and deep shadow"
    },
    {
        "id": "es_lengua_3_nebrija",
        "oldal": "es",
        "targy": "Lengua Castellana y Literatura",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Las lenguas y sus hablantes",
        "nev": "Elio Antonio de Nebrija",
        "alnev": "gramático · 1444–1522",
        "kep": "lengua_3_nebrija",
        "ritkasag": "nagyon_ritka",
        "ero": 420,
        "kepesseg": "La gramática",
        "kepesseg_ero": 350,
        "becenev": "EL QUE PUSO REGLAS",
        "leiras": "Escribió las primeras reglas del castellano: cómo se ordenan las palabras, cómo se escriben, por qué una frase suena bien.",
        "teny": "Su Gramática se publicó en 1492 y fue la primera gramática escrita de una lengua europea moderna. Hasta entonces solo se hacía con el latín.",
        "erdekesseg": "Cuando le preguntaron para qué servía aquello, contestó que la lengua siempre había acompañado al poder de un reino.",
        "idezet": "Siempre la lengua fue compañera del imperio.",
        "idezet_tipus": "idezet",
        "prompt": "a printed grammar book open on a lectern with a printing press behind it, and beside them Elio Antonio de Nebrija standing in a 15th-century print shop, the person's face fully visible and unobstructed, the book beside him not covering the face, an older scholar with a lined face and dark scholar's cap and gown, trays of metal type and freshly printed sheets hanging to dry, warm lamplight"
    },
    {
        "id": "es_lengua_3_lorca",
        "oldal": "es",
        "targy": "Lengua Castellana y Literatura",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Educación literaria",
        "nev": "Federico García Lorca",
        "alnev": "poeta y dramaturgo · 1898–1936",
        "kep": "lengua_3_lorca",
        "ritkasag": "nagyon_ritka",
        "ero": 410,
        "kepesseg": "La Barraca",
        "kepesseg_ero": 340,
        "becenev": "EL QUE LLEVÓ EL TEATRO AL PUEBLO",
        "leiras": "Escribió poemas y obras de teatro con el ritmo del habla popular andaluza, y consiguió que sonaran modernos y antiguos a la vez.",
        "teny": "Montó un teatro ambulante, La Barraca, y se recorrió los pueblos de España en camión representando obras clásicas gratis.",
        "erdekesseg": "Era muy buen pianista. Antes de dedicarse a escribir, recogió y armonizó canciones populares antiguas para que no se perdieran.",
        "idezet": "El teatro es la poesía que se levanta del libro y se hace humana.",
        "idezet_tipus": "idezet",
        "prompt": "a small wooden travelling stage on the back of an old truck with painted backdrops and a guitar leaning against it, and beside them Federico Garcia Lorca standing in a village square, the person's face fully visible and unobstructed, the stage behind him not covering the face, a young man with dark hair and thick eyebrows and a broad open face, plain blue workman's overall over a shirt, villagers gathering, bright dusty Castilian afternoon light"
    },
    {
        "id": "es_lengua_2_rosalia",
        "oldal": "es",
        "targy": "Lengua Castellana y Literatura",
        "ciklus": 2,
        "evfolyam": 4,
        "evfolyamok": [
            3,
            4
        ],
        "lecke": "Educación literaria",
        "nev": "Rosalía de Castro",
        "alnev": "poeta · 1837–1885",
        "kep": "lengua_2_rosalia",
        "ritkasag": "ritka",
        "ero": 330,
        "kepesseg": "Cantares gallegos",
        "kepesseg_ero": 270,
        "becenev": "LA VOZ DE GALICIA",
        "leiras": "Escribió poemas en gallego cuando casi nadie publicaba en esa lengua, y consiguió que volviera a considerarse una lengua de literatura.",
        "teny": "Su libro Cantares gallegos se publicó el 17 de mayo de 1863. Por eso Galicia celebra cada 17 de mayo el Día das Letras Galegas.",
        "erdekesseg": "Escribió mucho sobre los que se marchaban a trabajar fuera y sobre los que se quedaban esperando en el pueblo.",
        "idezet": "Adiós ríos, adiós fontes.",
        "idezet_tipus": "idezet",
        "prompt": "an open handwritten poetry notebook and a black shawl on a stone windowsill, and beside them Rosalia de Castro seated by the window of a Galician stone house, the person's face fully visible and unobstructed, the notebook beside her not covering the face, a serious young woman with dark hair parted in the middle, dark 19th-century dress with a lace collar, green rainy hills and a granary visible outside, soft grey northern light"
    },
    {
        "id": "es_lengua_3_sorjuana",
        "oldal": "es",
        "targy": "Lengua Castellana y Literatura",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Educación literaria",
        "nev": "Sor Juana Inés de la Cruz",
        "alnev": "poeta y pensadora · 1648–1695",
        "kep": "lengua_3_sorjuana",
        "ritkasag": "nagyon_ritka",
        "ero": 400,
        "kepesseg": "La biblioteca",
        "kepesseg_ero": 330,
        "becenev": "LA DÉCIMA MUSA",
        "leiras": "Fue la escritora más admirada de su tiempo en toda América y España, y defendió por escrito que las mujeres tenían derecho a estudiar.",
        "teny": "Reunió en su celda una biblioteca de miles de libros, además de instrumentos musicales y aparatos científicos.",
        "erdekesseg": "De niña pidió que la vistieran de chico para poder entrar en la universidad, porque a las chicas no se les permitía.",
        "idezet": "Hombres necios que acusáis a la mujer sin razón.",
        "idezet_tipus": "idezet",
        "prompt": "tall shelves of leather books, a globe and an open manuscript on a writing desk, and beside them Sor Juana Ines de la Cruz seated in her convent study, the person's face fully visible and unobstructed, the books beside her not covering the face, a young woman with a calm direct gaze in a white nun's habit with a large round medallion on the chest and a black veil, quill in hand, warm candlelight on colonial tiled walls"
    },
    {
        "id": "es_artistica_3_velazquez",
        "oldal": "es",
        "targy": "Educación Artística",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Artes plásticas, visuales y audiovisuales",
        "nev": "Diego Velázquez",
        "alnev": "pintor · 1599–1660",
        "kep": "artistica_3_velazquez",
        "ritkasag": "legendas",
        "ero": 470,
        "kepesseg": "Las Meninas",
        "kepesseg_ero": 390,
        "becenev": "EL PINTOR DEL REY",
        "leiras": "Pintó la luz y el aire como nadie lo había hecho antes: de cerca son manchas sueltas, y de lejos parece una fotografía.",
        "teny": "En Las Meninas se pintó a sí mismo trabajando dentro del propio cuadro, mirando de frente al que lo está mirando.",
        "erdekesseg": "Fue pintor del rey durante casi cuarenta años, y buena parte de su trabajo consistía en organizar las salas y las fiestas del palacio.",
        "idezet": "De cerca, manchas. De lejos, el aire.",
        "idezet_tipus": "jelmondat",
        "prompt": "a huge canvas on a wooden easel with a loaded palette and long brushes in the foreground, and beside them Diego Velazquez standing in a high palace room, the person's face fully visible and unobstructed, the canvas beside him not covering the face, dark curled hair and an upturned moustache, black 17th-century doublet with a white collar, tall shadowed room with a distant mirror, cool silvery daylight"
    },
    {
        "id": "es_artistica_3_goya",
        "oldal": "es",
        "targy": "Educación Artística",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Artes plásticas, visuales y audiovisuales",
        "nev": "Francisco de Goya",
        "alnev": "pintor y grabador · 1746–1828",
        "kep": "artistica_3_goya",
        "ritkasag": "nagyon_ritka",
        "ero": 430,
        "kepesseg": "Pinturas negras",
        "kepesseg_ero": 360,
        "becenev": "EL QUE PINTÓ LO QUE VIO",
        "leiras": "Empezó pintando fiestas alegres para la corte y acabó pintando la guerra y el miedo tal como eran, sin adornarlos.",
        "teny": "Una enfermedad le dejó sordo a los cuarenta y seis años. A partir de ahí su pintura se volvió mucho más oscura y mucho más libre.",
        "erdekesseg": "Ya mayor pintó una serie de cuadros directamente sobre las paredes de su casa, sin encargo y sin pensar en venderlos.",
        "idezet": "El sueño de la razón produce monstruos.",
        "idezet_tipus": "idezet",
        "prompt": "a copper etching plate and a burin on a workbench beside a wall half-covered with a dark unfinished mural, and beside them Francisco de Goya standing in his house, the person's face fully visible and unobstructed, the plate beside him not covering the face, an older man with wild grey hair and heavy brows and a stubborn stare, dark coat with a loose neckcloth, oil lamp light and deep brown shadow"
    },
    {
        "id": "es_artistica_2_sorolla",
        "oldal": "es",
        "targy": "Educación Artística",
        "ciklus": 2,
        "evfolyam": 4,
        "evfolyamok": [
            3,
            4
        ],
        "lecke": "Artes plásticas, visuales y audiovisuales",
        "nev": "Joaquín Sorolla",
        "alnev": "pintor · 1863–1923",
        "kep": "artistica_2_sorolla",
        "ritkasag": "ritka",
        "ero": 340,
        "kepesseg": "La luz",
        "kepesseg_ero": 280,
        "becenev": "EL PINTOR DE LA LUZ",
        "leiras": "Sacó el caballete a la playa y pintó al aire libre el sol sobre el agua, la ropa mojada y la arena caliente.",
        "teny": "Pasó ocho años pintando catorce paneles enormes con escenas de todas las regiones de España, y viajó a cada una para pintarla allí mismo.",
        "erdekesseg": "Pintaba muy rápido y de pie, porque decía que la luz cambia y no espera a nadie.",
        "idezet": "La luz cambia mientras la miras: hay que pintar deprisa.",
        "idezet_tipus": "jelmondat",
        "prompt": "a wooden easel planted in wet sand with a bright half-finished beach painting on it and a palette of white and blue, and beside them Joaquin Sorolla standing on the shore, the person's face fully visible and unobstructed, the easel beside him not covering the face, a middle-aged man with a dark moustache and a straw hat, white shirt with rolled sleeves, sea foam and children's shapes in the distance, dazzling Mediterranean midday light"
    },
    {
        "id": "es_artistica_3_falla",
        "oldal": "es",
        "targy": "Educación Artística",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Música y artes escénicas y performativas",
        "nev": "Manuel de Falla",
        "alnev": "compositor · 1876–1946",
        "kep": "artistica_3_falla",
        "ritkasag": "ritka",
        "ero": 350,
        "kepesseg": "El amor brujo",
        "kepesseg_ero": 290,
        "becenev": "EL QUE ESCRIBIÓ EL FUEGO",
        "leiras": "Convirtió el flamenco y la música popular andaluza en música de orquesta, sin quitarle la fuerza que tenía.",
        "teny": "Su Danza ritual del fuego, de El amor brujo, es una de las piezas españolas más tocadas del mundo.",
        "erdekesseg": "Organizó en Granada, junto con Lorca, un concurso para rescatar el cante jondo antiguo antes de que se perdiera.",
        "idezet": "La música popular no se copia: se escucha y se sigue.",
        "idezet_tipus": "jelmondat",
        "prompt": "a hand-written orchestral score on a piano music stand with a guitar leaning against the piano, and beside them Manuel de Falla seated at the keyboard in a Granada house, the person's face fully visible and unobstructed, the piano beside him not covering the face, a small thin man with a bald head and sharp features and a dark suit, whitewashed walls and a window onto a garden with cypresses, warm southern evening light"
    },
    {
        "id": "es_artistica_2_albeniz",
        "oldal": "es",
        "targy": "Educación Artística",
        "ciklus": 2,
        "evfolyam": 4,
        "evfolyamok": [
            3,
            4
        ],
        "lecke": "Música y artes escénicas y performativas",
        "nev": "Isaac Albéniz",
        "alnev": "compositor y pianista · 1860–1909",
        "kep": "artistica_2_albeniz",
        "ritkasag": "ritka",
        "ero": 320,
        "kepesseg": "Iberia",
        "kepesseg_ero": 260,
        "becenev": "EL NIÑO DEL PIANO",
        "leiras": "Escribió para piano piezas que suenan a guitarra española, a fiesta y a calle, y que hoy tocan pianistas de todo el mundo.",
        "teny": "Su obra Iberia son doce piezas tan difíciles que él mismo dudó de si alguien podría tocarlas.",
        "erdekesseg": "Era un niño prodigio y daba conciertos siendo muy pequeño. De mayor le encantaba contar historias exageradas sobre sus viajes de infancia.",
        "idezet": "Doce piezas que casi nadie podía tocar.",
        "idezet_tipus": "jelmondat",
        "prompt": "an open grand piano with hand-written sheet music on the stand and a Spanish guitar propped against its leg, and beside them Isaac Albeniz seated at the keys, the person's face fully visible and unobstructed, the piano beside him not covering the face, a stout man with a thick dark moustache and a genial face, dark late-19th-century suit, a warm room with heavy curtains, golden lamplight"
    },
    {
        "id": "es_efisica_3_coubertin",
        "oldal": "es",
        "targy": "Educación Física",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Manifestaciones de la cultura motriz",
        "nev": "Pierre de Coubertin",
        "alnev": "pedagogo · 1863–1937",
        "kep": "efisica_3_coubertin",
        "ritkasag": "ritka",
        "ero": 330,
        "kepesseg": "Los Juegos",
        "kepesseg_ero": 270,
        "becenev": "EL QUE VOLVIÓ A ENCENDER LA LLAMA",
        "leiras": "Convenció a media Europa de recuperar los Juegos Olímpicos después de mil quinientos años sin celebrarse.",
        "teny": "Los primeros Juegos modernos se celebraron en Atenas en 1896, dos años después de que él fundara el Comité Olímpico Internacional.",
        "erdekesseg": "Hizo famosa la frase de que lo importante no es ganar sino participar, aunque no fue él quien la dijo primero: la escuchó en un sermón.",
        "idezet": "Lo importante no es ganar, sino participar.",
        "idezet_tipus": "idezet",
        "prompt": "a laurel wreath and an unrolled olympic charter on a stone bench in front of ancient stadium ruins, and beside them Pierre de Coubertin standing in Olympia, the person's face fully visible and unobstructed, the wreath beside him not covering the face, a small man with a very large dark moustache and a formal 1890s suit and hat, marble columns and dry grass, clear Greek morning light"
    },
    {
        "id": "es_extranjera_3_battuta",
        "oldal": "es",
        "targy": "Lengua Extranjera",
        "ciklus": 3,
        "evfolyam": 6,
        "evfolyamok": [
            5,
            6
        ],
        "lecke": "Interculturalidad",
        "nev": "Ibn Battuta",
        "alnev": "viajero y cronista · 1304–1368",
        "kep": "extranjera_3_battuta",
        "ritkasag": "nagyon_ritka",
        "ero": 400,
        "kepesseg": "La Rihla",
        "kepesseg_ero": 330,
        "becenev": "EL QUE NO PARABA",
        "leiras": "Se pasó veintinueve años viajando y recorrió unos ciento veinte mil kilómetros, mucho más que ningún otro viajero de su época.",
        "teny": "A la vuelta le dictó todo a un escribano. Ese libro, la Rihla, cuenta cómo se comía, se rezaba y se hablaba en decenas de países.",
        "erdekesseg": "Salió de casa a los veintiún años pensando en hacer un solo viaje. Volvió con el pelo gris.",
        "idezet": "Salí solo, sin compañero de viaje y sin caravana.",
        "idezet_tipus": "idezet",
        "prompt": "a worn leather travel satchel, a rolled map and a walking staff resting against a stone wall, and beside them Ibn Battuta standing at a caravanserai gate, the person's face fully visible and unobstructed, the satchel beside him not covering the face, a bearded traveller in a dusty cream robe and turban, camels and a busy market street behind him, warm dusty afternoon light"
    }
]
